export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://loparskoguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/loparskor","priority":"0.8","changefreq":"weekly"},{"path":"/smartwatch","priority":"0.8","changefreq":"weekly"},{"path":"/cykel","priority":"0.8","changefreq":"weekly"},{"path":"/traning","priority":"0.8","changefreq":"weekly"},{"path":"/outdoor","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-adidas-ultraboost-24","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-asics-gel-kayano-29","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-saucony-endorphin-pro-4","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-brooks-ghost-16","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-hoka-one-one-clifton-10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nike-zoomx-vaporfly-next-3-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/adidas-ultraboost-24-vs-asics-gel-kayano-29","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/adidas-ultraboost-24-vs-saucony-endorphin-pro-4","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/adidas-ultraboost-24-vs-brooks-ghost-16","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/adidas-ultraboost-24-vs-hoka-one-one-clifton-10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/adidas-ultraboost-24-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/asics-gel-kayano-29-vs-saucony-endorphin-pro-4","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/asics-gel-kayano-29-vs-brooks-ghost-16","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/asics-gel-kayano-29-vs-hoka-one-one-clifton-10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/asics-gel-kayano-29-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/saucony-endorphin-pro-4-vs-brooks-ghost-16","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/saucony-endorphin-pro-4-vs-hoka-one-one-clifton-10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/saucony-endorphin-pro-4-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/brooks-ghost-16-vs-hoka-one-one-clifton-10","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/brooks-ghost-16-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hoka-one-one-clifton-10-vs-new-balance-fresh-foam-1080v13","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }